### ISSUE TITLE
520: Origin Error and Reached retry limit

### ISSUE THREAD

**Issue by GohJazn** [thatJavaNerd/JRAW#156]
Hello, I am not sure if this error is reddit related, JRAW related, or my code related but whenever I call the loadMoreComments on the submission root comment node, after a few seconds I get the following error:

`java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
                                                                              Caused by: java.lang.IllegalStateException: Reached retry limit
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:153)
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:155)
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:155)
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:155)
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:155)
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:155)
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:155)
                                                                                 at net.dean.jraw.RedditClient.execute(RedditClient.java:137)
                                                                                 at net.dean.jraw.models.CommentNode.getMoreComments(CommentNode.java:422)
                                                                                 at net.dean.jraw.models.CommentNode.loadMoreComments(CommentNode.java:275)`

However, this error occurs when I am trying to load more comments in a submission with a lot of comments in it. With submissions with not that much comments, it loads them just fine. 

This is the part of my program where it is causing the error:

`

 private void loadMoreEndComments() {

        new AsyncTask<Void, Void, Void>() {

            @Override
            protected Void doInBackground(Void... params) {

                mRootNode.loadMoreComments(mRedditClient) ; // Right here seems to be the issue.

                //Log.d("TAG",moreComments.toString());

                Iterable<CommentNode> iterable = mRootNode.walkTree();

                for (CommentNode node :iterable) {

                    Comment comment = new Comment();

                    net.dean.jraw.models.Comment nodeComment = node.getComment();

                    if(!checkIfExsist(nodeComment)) {....}
                   
                }

            }
        }
} 

`

**Comment by thatJavaNerd** [comment]
An HTTP 520 code is a CloudFlare error. There isn't anything you can do about this, it's a server-side issue.

**Comment by GohJazn** [comment]
Ah I see. The 520 status code has seem to have gone away now. However,  strangely now I get a 400 status code when trying to use loadMoreComments() on posts with 7k+ comments. That seems to be a bad request error, but only for loadMoreComments requests on posts with tons of comments.

**Comment by GohJazn** [comment]
Hmm, it seems like my issue is similar to #120 if not the exact same scenario, but it still persists for me. I believe I have the latest version of JRAW so if it is fixed, then it must be something on my end maybe.

**Comment by thatJavaNerd** [comment]
From README.md:

>`gradle release` will generate four Jar files in `build/releases`: a normal jar with just the library, a "fat" jar with all of JRAW's runtime dependencies, a Javadoc jar, and a sources jar.

Include the fat jar into an isolated project where you can test it.

**Comment by GohJazn** [comment]
Thank you for your help. Closing now.
