### ISSUE TITLE
After one hour script Credentials Timeout and throw 401 Unauthorized.

### ISSUE THREAD

**Issue by bobloki** [thatJavaNerd/JRAW#168]
This is the code I'm using for my script.
```
UserAgent myUserAgent = UserAgent.of("desktop", "Censorship", "v0.1", accounts[0]);
RedditClient redditClient = new RedditClient(myUserAgent);
			
Credentials credentials = Credentials.script //...
OAuthData authData;
			
authData = redditClient.getOAuthHelper().easyAuth(credentials);
redditClient.authenticate(authData);
```

This is the code I've tried to use to renew the token.
```
redditClient.getOAuthHelper().revokeAccessToken(credentials);
redditClient.getOAuthHelper().revokeRefreshToken(credentials);
redditClient.deauthenticate();
						
authData = redditClient.getOAuthHelper().easyAuth(credentials);
redditClient.authenticate(authData);
```

This is the exception I am getting:

```
net.dean.jraw.http.NetworkException: Request returned non-successful status code: 401 Unauthorized
	at net.dean.jraw.http.RestClient.execute(RestClient.java:132)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:143)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:137)
	at net.dean.jraw.paginators.Paginator.next(Paginator.java:109)
	at net.dean.jraw.paginators.SubredditPaginator.next(SubredditPaginator.java:51)
	at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
	at SubRedditController.run(Main.java:421)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by thatJavaNerd** [comment]
What line is 421?

**Comment by bobloki** [comment]
List<Submission> previous50 = paginator.next();

**Comment by Hronom** [comment]
Have same problem...

**Comment by thatJavaNerd** [comment]
OAuth tokens expire after one hour. In your case since your app is a script, you must request a whole new token. For installed or web apps, you can request a refresh token when you call [`OAuthHelper.getAuthorizationUrl`](https://thatjavanerd.github.io/JRAW/docs/latest/net/dean/jraw/http/oauth/OAuthHelper.html#getAuthorizationUrl(net.dean.jraw.http.oauth.Credentials,%20boolean,%20java.lang.String...)).

**Comment by Hronom** [comment]
@thatJavaNerd I use `userlessApp`
```Java
UserAgent myUserAgent = UserAgent.of("desktop", "TestApp", "v1.0.1", redditUsername);
RedditClient redditClient = new RedditClient(myUserAgent);
Credentials credentials = Credentials.userlessApp(clientId, UUID.randomUUID());
OAuthData authData = redditClient.getOAuthHelper().easyAuth(credentials);
redditClient.authenticate(authData);
```
how to make refresh in this case?

**Comment by bobloki** [comment]
@thatJavaNerd I see that @Hronom has a userlessApp and I have a script.

Is there a simple way to request a new token for the same RedditClient object?

This is the code that I was using to attempt to get a new token:

```
redditClient.getOAuthHelper().revokeAccessToken(credentials);`
redditClient.getOAuthHelper().revokeRefreshToken(credentials);
redditClient.deauthenticate();
						
authData = redditClient.getOAuthHelper().easyAuth(credentials);
redditClient.authenticate(authData)
```

**Comment by wadeAlexC** [comment]
I am using a script as well and am unable to figure out how to request a new token.

The code I am using to request a new token so far - 

client.authenticate(client.getOAuthHelper().refreshToken(creds));

**Comment by bobloki** [comment]
This is what I went with to fix the problem.  I literally just revoke the tokens, deauthenticate, kill the thread, and start a new one.

```
redditClient.getOAuthHelper().revokeAccessToken(credentials);
redditClient.getOAuthHelper().revokeRefreshToken(credentials);
redditClient.deauthenticate();
SubRedditController src = new SubRedditController(subreddit, previous50);
new Thread(src).start();
						
return;
```
