### ISSUE TITLE
NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire()

### ISSUE THREAD

**Issue by David-Rohatschek** [thatJavaNerd/JRAW#178]
I'm having issues while connecting to Reddit. Here is the implementation:

```scala
 private val lioncubConf = Configuration
 private val userAgent = UserAgent.of("desktop", lioncubConf.redditID, "v0.1", lioncubConf.redditUser)
 private val redditClient = initRedditApi()
 

  private def initRedditApi(): RedditClient = {
    val redditClient = new RedditClient(userAgent)
    val credentials = Credentials.script(lioncubConf.redditUser, lioncubConf.redditPassword, lioncubConf.redditID, lioncubConf.redditSecret)
    val oAuth = redditClient.getOAuthHelper.easyAuth(credentials)
    redditClient.authenticate(oAuth)
    redditClient
  } 

```

It gives me an NoSuchMethodError which is thrown by this statement ` redditClient.authenticate(oAuth) `. 

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire()D
	at net.dean.jraw.http.RestClient.execute(RestClient.java:108)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:143)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:137)
	at net.dean.jraw.RedditClient.me(RedditClient.java:236)
	at net.dean.jraw.RedditClient.authenticate(RedditClient.java:109)
	at hfu.lioncub.RedditAccess.initRedditApi(RedditAccess.scala:28)
	at hfu.lioncub.RedditAccess.<init>(RedditAccess.scala:16)
	at hfu.lioncub.RedditBot$.main(RedditBot.scala:23)
	at hfu.lioncub.RedditBot.main(RedditBot.scala)
```

The problem is caused by the Guava API. But I don't accutally know the reason for that behaviour. I checked that the dependencies  where resolved correctly. And I also checked the Javadoc. The method should exist.
I used the fat jar of version 0.9.0 you provided. I also tried to use the maven to solve the dependencies. Do you have any idea what went wrong?

**Comment by David-Rohatschek** [comment]
I solved the problem. I had a merge conflict using the scala build tool, which was solved in the wrong way.
