### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by DVassilev** [thatJavaNerd/JRAW#93]
Hi,

What causes this error:

```
Caused by: net.dean.jraw.http.NetworkException: Request returned non-successful status code: 403 Forbidden
```

It comes and goes so I don't think it could be an issue with authentication.

Thanks,
Daniel

**Comment by thatJavaNerd** [comment]
Can you provide the relevant code and stacktrace?

**Comment by DVassilev** [comment]
@thatJavaNerd 
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by net.dean.jraw.http.NetworkException: Request returned non-successful status code: 403 Forbidden
       at net.dean.jraw.http.RestClient.execute(RestClient.java:132)
       at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
       at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
       at net.dean.jraw.paginators.Paginator.next(Paginator.java:109)
       at net.dean.jraw.paginators.SubredditPaginator.next(SubredditPaginator.java:53)
       at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
       at org.vylar.reelforreddit.hover.ReelService$UpdateReel.doInBackground(ReelService.java:291)
       at org.vylar.reelforreddit.hover.ReelService$UpdateReel.doInBackground(ReelService.java:227)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

and relevant code:

```
@Override
protected Listing<Submission> doInBackground(Void... params) {

     listings = subredditPaginator.next(); // line 291

     return listings;
}

where

application = (ReelForReddit) getApplication();
subredditPaginator = new SubredditPaginator(application.getRedditClient());
```

**Comment by DVassilev** [comment]
An issue may be that the activity doesn't get closed so theoretically it stays open once the token has expired (as authentication is done by a previous activity). I have made it close so that each time the app is opened it goes through authentication to see if it makes a difference.

**Comment by DVassilev** [comment]
@thatJavaNerd Unfortunately even after the changes above it still sometimes presents that error. I cannot reproduce it myself but notice a large percentage of people are affected by this.

**Comment by l3d00m** [comment]
It happens for me when a suberddit is a private subreddit. Then it throws a 403 Forbidden Network Exception
